# mkdocs.yml
site_name: Arena Rosnav

nav:
  - Introduction: "index.md"
  - Publications: "publications.md"
  - Contribute: "contribute.md"

  - User Guides:
      - Installation: "user_guides/installation.md"
      - Planners: "user_guides/planners_overview.md"
      - Usage: "user_guides/usage.md"
      - Training: "user_guides/training.md"
  -System Design:
      - Overall System Design: "system/system-desing.md"
      - Training Pipeline: "system/training-design.md"
      - Launch File System: "system/launch-file-design.md"
      - Evaluation/Benchmarking Pipeline: "system/eval-design.md"
  - Packages:
      - Task Generator: "packages/task_generator.md"
      - Arena Simulation Setup: "packages/arena_simulation_setup.md"
      - Evaluation: "packages/arena_evaluation.md"
      - ROSNavRL: "packages/rosnavrl.md"

  - Tutorials:
      - Add new environment: "tutorials/add_new_environment.md"
      - Train an agent with different observation spaces: "tutorials/train_agent_with_different_observation_spaces.md"
  
  # - User Guides:
  #     - Installation: "user_guides/installation.md"
  #     - Get Started: "user_guides/get_started.md"
  #     - Error Handling: "user_guides/error_handling.md"
  #     - Arena Tools: "user_guides/arena-tools.md"
  # - Arena-Rosnav Overview:
  #     - Modular Structure: "overview/modular_structure.md"
  #     - Planners: "overview/planners.md"
  #     - Simulation Environments: "overview/simulation_environments.md"
  #     - General Utils: "overview/general_utils.md"
  # - Core Functionalities:
  #     - Launching Arena-Rosnav Simulation: "core_functionalities/launch_simulation.md"
  #     - Training an Agent: "core_functionalities/training.md"
  #     - Evaluating Planner Performance: "core_functionalities/evaluation.md"

markdown_extensions:
  - admonition
  - tables

theme:
  name: readthedocs

plugins:
  - mkdocs-video:
      is_video: true
      video_type: webm

extra_css:
  - css/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.6.0/clipboard.min.js
  - js/cpybtn.js
