site_name: arena-rosnav wiki
nav:
  - Home: 'docs/index.md'
  - Modules: 'docs/modules.md'
  - Installation: 'docs/installation.md'
  - Get Started: 'docs/get_started.md'

markdown_extensions:
  - admonition

theme:
  name: readthedocs