# mkdocs.yml
site_name: Arena-Rosnav wiki

nav:
  - User Guides:
    - Installation: 'installation.md'
    - Get Started: 'get_started.md'
    - Error Handling: 'error_handling.md'
  - Arena-Rosnav Overview:
    - Modular Structure: 'overview/modular_structure.md'
    - Planners: 'overview/planners.md'
    - Simulation Environments: 'overview/simulation_environments.md'
    - General Utils: 'overview/general_utils.md'
  - Core Functionalities:
    - Launching Arena-Rosnav Simulation: "core_functionalities/launch_simulation.md"
    - Training an Agent: "core_functionalities/training.md"
    - Evaluating Planner Performance: "core_functionalities/evaluation.md"
    - Arena Tools: "core_functionalities/arena-tools.md"
markdown_extensions:
  - admonition
  - tables

theme:
  name: readthedocs

plugins:
  - mkdocs-video:
      is_video: true
      video_type: webm