# mkdocs.yml
site_name: Arena 4.0

nav:
  - Introduction: "tutorials/usage.md"
  - Publications: "publications.md"
  - Contribute: "contribute.md"

  - Tutorials:
      - Installation: "tutorials/installation.md"
      - Getting Started: "tutorials/usage.md"
      - Simulation: "tutorials/simulation/index.md"
      - Tasks: "tutorials/tasks/index.md"
      - Planners: "tutorials/planners/index.md"

markdown_extensions:
  - admonition
  - tables

theme:
  name: readthedocs

plugins:
  - mkdocs-video:
      is_video: true
      video_type: webm

extra_css:
  - css/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.6.0/clipboard.min.js
  - js/cpybtn.js
